# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

- task: CmdLine@2
  displayName: 'Replace SSH links'
  inputs:
    script: 'git config --global url."https://github".insteadOf ssh://git@github'

- task: NodeTool@0
  inputs:
    versionSpec: '16.17.0'
  displayName: 'Install Node.js'

- task: Yarn@3
  displayName: 'Yarn Install'
  inputs:
    projectDirectory: './'
    arguments: 'install'

- task: Yarn@3
  displayName: 'Yarn Filters-convert'
  inputs:
    projectDirectory: './'
    arguments: 'filters-convert'

- task: Yarn@3
  displayName: 'Yarn Build'
  inputs:
    projectDirectory: './'
    arguments: 'release'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\build'
    ArtifactName: 'extensiondrop'
    publishLocation: 'Container'